---
abstract: 'Determine if a string looks like a perl warning'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Perl-Warnings
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  String::Perl::Warnings:
    file: lib/String/Perl/Warnings.pm
    version: 1.02
requires:
  Regexp::Assemble: 0.34
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/string-perl-warnings/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/string-perl-warnings.git
version: 1.02
